### ISSUE TITLE
Rendering virtual scenes appears to be broken

### ISSUE THREAD

**Issue by DavidBrainard** [RenderToolbox3/VirtualScenes#7]
A) When I run ExecuteManyWardLandRecipes after first running MakeManyWardLandRecipes, the rendering fails.  The output from the command window is below.  My guess is that this is some pesky little thing that either crept in with recent changes to RTB itself, or arises because I did something wrong in the configuration.  Ben, can you see if you can replicate this error and if so fix it?  If it works for you, then we'll need to dig deeper into my configuration.

B) I get a different error when I try to run MakeWardLandReferenceRecipes (and similary with MakeWardLandTextureRecipe). Output from that also below, after the output for A.

***\* Command Window output for A (just for first scene, similarly for following scenes ****
MakeSceneFiles started at 27-Feb-2016 10:24:17.

Original Collada scene authored with Blender 2.69.0 r60991.

Skipping optional Remodeler API function (not found): RTB_BeforeAll_InsertObjectRemodeler

MakeSceneFiles started with isParallel=0 at 27-Feb-2016 10:24:19.

Skipping optional Remodeler API function (not found): RTB_AfterCondition_InsertObjectRemodeler
Converting /Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/IBIO_data/virtual-scenes/working/CheckerBoard-00-Obj-00-Illum/temp/Mitsuba/CheckerBoard-matte-7bit-clean-BeforeCondition.dae
  to /Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/IBIO_data/virtual-scenes/working/CheckerBoard-00-Obj-00-Illum/scenes/Mitsuba/matte.xml.
Scene conversion error!
Mitsuba file conversion failed
  /Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/IBIO_data/virtual-scenes/working/CheckerBoard-00-Obj-00-Illum/temp/Mitsuba/CheckerBoard-matte-7bit-clean-BeforeCondition.dae
  /bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0:`/Applications/Mitsuba.app/Contents/MacOS/mtsimport -r 160x120 -l hdrfilm /Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/IBIO_data/virtual-scenes/working/CheckerBoard-00-Obj-00-Illum/temp/Mitsuba/CheckerBoard-matte-7bit-clean-BeforeCondition.dae /Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/IBIO_data/virtual-scenes/working/CheckerBoard-00-Obj-00-Illum/temp/Mitsuba/matteUnadjusted.xml'

***\* Command Window output for B ****
Undefined operator '+' for input arguments of type 'struct'.

Error in GetWardLandIlluminantSpectra (line 53)
temps = mean + std .\* randn([1, nSpectra]);

Error in MakeWardLandReferenceRecipes (line 36)
lightSpectra = GetWardLandIlluminantSpectra(hints);

**Comment by benjamin-heasly** [comment]
Hi David,

For part A, it looks like the problem is a space in the VirtualScenes recipesFolder:

```
/Volumes/Users1/Dropbox (Aguirre-Brainard Lab)/...
```

I was able to get a similar error on my end by adding a space to my recipes folder.  My configuration script looked like this:

```
% where to save recipe archives
setpref(prefName, 'recipesFolder', ...
    fullfile(GetUserFolder(), 'virtual-scenes space', 'recipe-archives'));

% where to put the RenderToolbox3 working folder
setpref(prefName, 'workingFolder', ...
    fullfile(GetUserFolder(), 'virtual-scenes space', 'working'));
```

So I think I/we didn't anticipate file paths with spaces.

I updated the Mitsuba import and rendering commands to add quotes around file names.  This seems to have fixed the problem for me.  I can now run MakeManyWardLandRecipes and ExecuteManyWardLandRecipes with a space in the path, and no error.

Here is a small [PR](https://github.com/RenderToolbox3/RenderToolbox3/pull/44) for RenderToolbox3 with the change.  Would you mind taking a look and doing the merge if it looks good?

I know it's a small change and the PR may be overkill.  But I really like the idea of communicating about the code this way.

**Comment by benjamin-heasly** [comment]
Part B looks like a good old fashioned regression bug :-1: 

It looks like I had changed the inputs to a function, but only updated the calling code in one place.

I found-and-updated the calling code in other places.

Now I am able to run MakeWardLandReferenceRecipes, ExecuteWardLandReferenceRecipes, MakeWardLandTextureRecipe, and ExecuteWardLandTextureRecipe, all without error. :+1: 

Here is a [PR]() for VirutalScenes.  Again, would you mind reviewing it and merging if it LG2U?

**Comment by DavidBrainard** [comment]
I can’t find the actual pull request — the link in this email doesn’t go anywhere and there aren’t any open PR’s under VirtualWorlds.

I am about to get on an airplane.  Ben, I’d say go ahead and accept this yourself and if there are problems we’ll deal with it later.

Best,

David

On Mar 1, 2016, at 12:19 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Part B looks like a good old fashioned regression bug [:-1:]

It looks like I had changed the inputs to a function, but only updated the calling code in one place.

I found-and-updated the calling code in other places.

Now I am able to run MakeWardLandReferenceRecipes, ExecuteWardLandReferenceRecipes, MakeWardLandTextureRecipe, and ExecuteWardLandTextureRecipe, all without error. [:+1:]

Here is a PR for VirutalScenes. Again, would you mind reviewing it and merging if it LG2U?

**Comment by benjamin-heasly** [comment]
My mistake.  I'll create the PR and wrap it up.

**Comment by benjamin-heasly** [comment]
Sorry about that.  Here is the real [PR](https://github.com/RenderToolbox3/VirtualScenes/pull/8)
